FROM node:20-alpine

ARG VITE_API_BASE_URL=https://arabic-home-system-backend-6tpv-production.up.railway.app/api
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm install

COPY frontend .

RUN npm run build

FROM nginx:1.27-alpine
RUN apk add --no-cache gettext
COPY --from=0 /app/frontend/dist /usr/share/nginx/html
COPY frontend/nginx.conf.template /etc/nginx/templates/nginx.conf.template
COPY frontend/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
