FROM node:20-alpine

ARG VITE_API_BASE_URL=/api
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm install

COPY frontend .

RUN npm run build

FROM nginx:1.27-alpine
COPY --from=0 /app/frontend/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
