# Generated by Django 5.2.17 on 2026-09-14 12:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_file',
            field=models.FileField(blank=True, upload_to='exams/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for submissions'), ('closed', 'Closed')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.level'),
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exam')),
            ],
            options={
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('exam', 'order'), name='unique_exam_section_order'), models.UniqueConstraint(fields=('exam', 'name'), name='unique_exam_section_name')],
            },
        ),
    ]
