# Generated by Django 5.2.17 on 2026-09-23 22:39

import apps.core.file_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_file',
            field=models.FileField(blank=True, upload_to='exams/', validators=[apps.core.file_validation.validate_pdf_file]),
        ),
    ]
