# Generated by Django 5.2.17 on 2026-09-30 16:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_legacy_pdf_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for submissions'), ('closed', 'Closed'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True or false'), ('short_answer', 'Short answer'), ('written', 'Written answer')], max_length=20)),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveIntegerField()),
                ('answer_text', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.examsection')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='unique_section_question_order'),
        ),
        migrations.AddConstraint(
            model_name='questionchoice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_question_choice_order'),
        ),
    ]
