# Generated by Django 5.2.17 on 2026-10-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_examsection_name'),
        ('results', '0007_delete_sectionscore'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_section_question_order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('bank_order', 'order', 'id')},
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ExamSection',
        ),
    ]
