# Generated by Django 5.2.17 on 2026-10-03 18:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_questionsource_question_source_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_count',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_score',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='ExamSourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_allocations', to='exams.exam')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_allocations', to='exams.questionsource')),
            ],
            options={
                'ordering': ('source__subject__name', 'source__original_filename'),
                'constraints': [models.UniqueConstraint(fields=('exam', 'source'), name='unique_exam_question_source')],
            },
        ),
    ]
