# Generated by Django 5.2.17 on 2026-10-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0011_exam_question_count_alter_exam_max_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_order", models.PositiveIntegerField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_questions",
                        to="exams.exam",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selected_for_exams",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exam", "question"),
                        name="unique_exam_selected_question",
                    ),
                    models.UniqueConstraint(
                        fields=("exam", "display_order"),
                        name="unique_exam_selected_order",
                    ),
                ],
            },
        ),
    ]
