# Generated by Django 5.2.17 on 2026-10-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptquestion',
            name='points_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
